import {
  MessageSquare,
  Workflow,
  HeartPulse,
  BookOpen,
  TrendingUp,
  Palette,
  Code2,
  Bot,
  Search,
  PenTool,
  Video,
  Microscope,
  Scale,
  Target,
  Headphones,
  Users,
  Languages,
  FileText,
  Mic,
  FileEdit,
  Table2,
  Presentation,
  Mail,
  CalendarDays,
  CheckSquare,
  BarChart3,
  Globe,
  Bug,
  Rocket,
  Activity,
  Shield,
  Database,
  ArrowRightLeft,
  DollarSign,
  Leaf,
  FileCheck,
  ScanLine,
  ScrollText,
  GraduationCap,
  UserPlus,
  UserCheck,
  UserX,
  Package,
  Network,
  Boxes,
  Award,
  Wrench,
  Map,
  Building2,
  Truck,
  Zap,
  Droplets,
  Recycle,
  Building,
  LayoutGrid,
  FileSignature,
  Handshake,
  type LucideIcon,
} from "lucide-react";

export interface App {
  id: string;
  name: string;
  tagline: string;
  description: string;
  features: string[];
  version: string;
  icon: LucideIcon;
  color: string;
  bgColor: string;
  domain: string;
  category: string;
  status: "live" | "beta" | "coming_soon";
}

export const apps: App[] = [
  {
    id: "chat",
    name: "DClaw Chat",
    tagline: "AI conversations that remember",
    description:
      "A multi-model AI chat interface with persistent memory, voice input, and local or cloud LLM support. Switch between Ollama, OpenRouter, and proprietary models on the fly.",
    features: [
      "Multi-model chat (Ollama, OpenRouter, Claude, GPT-4)",
      "Persistent conversation history",
      "Voice input and speech-to-text",
      "Desktop app via Tauri",
      "End-to-end encrypted messaging",
    ],
    version: "1.0.0",
    icon: MessageSquare,
    color: "#3B82F6",
    bgColor: "rgba(59, 130, 246, 0.15)",
    domain: "localhost:30002",
    category: "Communication",
    status: "live",
  },
  {
    id: "flow",
    name: "DClaw Flow",
    tagline: "Connect anything, automate everything",
    description:
      "Visual workflow builder with AI-powered node generation. Connect APIs, databases, and services with drag-and-drop simplicity.",
    features: [
      "Visual node editor",
      "AI-generated workflow suggestions",
      "Webhook triggers and scheduled jobs",
      "200+ native integrations",
      "Real-time execution monitoring",
    ],
    version: "0.1.0",
    icon: Workflow,
    color: "#10B981",
    bgColor: "rgba(16, 185, 129, 0.15)",
    domain: "localhost:30003",
    category: "Automation",
    status: "live",
  },
  {
    id: "med",
    name: "DClaw Med",
    tagline: "Clinical intelligence at your fingertips",
    description:
      "HIPAA-compliant AI assistant for healthcare professionals. Clinical decision support, medical literature search, and patient note generation.",
    features: [
      "HIPAA-compliant data handling",
      "Clinical decision support",
      "Medical literature RAG search",
      "Patient note auto-generation",
      "Drug interaction checking",
    ],
    version: "0.1.0",
    icon: HeartPulse,
    color: "#EF4444",
    bgColor: "rgba(239, 68, 68, 0.15)",
    domain: "localhost:30004",
    category: "Healthcare",
    status: "live",
  },
  {
    id: "learn",
    name: "DClaw Learn",
    tagline: "Adaptive learning that works",
    description:
      "AI tutor that adapts to your learning style. Upload any material and get personalized study plans, quizzes, and explanations.",
    features: [
      "Adaptive learning paths",
      "Upload PDFs, videos, or notes",
      "Auto-generated quizzes",
      "Spaced repetition scheduling",
      "Progress analytics dashboard",
    ],
    version: "0.1.0",
    icon: BookOpen,
    color: "#3B82F6",
    bgColor: "rgba(59, 130, 246, 0.15)",
    domain: "localhost:30005",
    category: "Education",
    status: "live",
  },
  {
    id: "seo",
    name: "DClaw SEO",
    tagline: "Rank higher with AI",
    description:
      "Autonomous SEO agent that audits your site, optimizes content, and tracks rankings. Complete technical SEO and content strategy in one tool.",
    features: [
      "Full site technical audits",
      "AI content optimization",
      "Competitor keyword analysis",
      "Rank tracking and alerts",
      "Automated backlink outreach",
    ],
    version: "0.1.0",
    icon: TrendingUp,
    color: "#10B981",
    bgColor: "rgba(16, 185, 129, 0.15)",
    domain: "localhost:30006",
    category: "Marketing",
    status: "live",
  },
  {
    id: "create",
    name: "DClaw Create",
    tagline: "Generate anything",
    description:
      "Multimodal AI content studio. Generate images, video, audio, 3D models, and code from natural language prompts.",
    features: [
      "Text-to-image generation",
      "Text-to-video synthesis",
      "Voice cloning and TTS",
      "3D model generation",
      "Batch processing pipeline",
    ],
    version: "0.1.0",
    icon: Palette,
    color: "#EC4899",
    bgColor: "rgba(236, 72, 153, 0.15)",
    domain: "localhost:30007",
    category: "Media",
    status: "live",
  },
  {
    id: "code",
    name: "DClaw Code",
    tagline: "AI-native IDE inside your desktop",
    description:
      "A desktop IDE built for the AI era. Inline copilot, multi-file refactoring, and autonomous agent coding with full project context.",
    features: [
      "Inline AI copilot",
      "Multi-file refactoring",
      "Autonomous coding agents",
      "Local and remote dev environments",
      "Built-in terminal and debugger",
    ],
    version: "0.1.0",
    icon: Code2,
    color: "#1F2937",
    bgColor: "rgba(31, 41, 55, 0.15)",
    domain: "localhost:30012",
    category: "Development",
    status: "live",
  },
  {
    id: "agent",
    name: "DClaw Agent",
    tagline: "Build, share, and sell AI agents",
    description:
      "Agent marketplace and builder. Create custom AI agents with no-code tools, share them with the community, or sell them in the marketplace.",
    features: [
      "No-code agent builder",
      "Agent marketplace",
      "Revenue sharing for creators",
      "Agent-to-agent communication",
      "Usage analytics and billing",
    ],
    version: "0.1.0",
    icon: Bot,
    color: "#8B5CF6",
    bgColor: "rgba(139, 92, 246, 0.15)",
    domain: "localhost:30091",
    category: "Platform",
    status: "live",
  },
  {
    id: "rag",
    name: "DClaw RAG",
    tagline: "Universal knowledge retrieval",
    description:
      "Connect any data source — documents, databases, APIs — and get accurate, cited answers with full provenance. Enterprise-grade RAG without the complexity.",
    features: [
      "Multi-source data connectors",
      "Vector search with citations",
      "Real-time sync from APIs",
      "Custom embedding models",
      "Access control and audit logs",
    ],
    version: "0.1.0",
    icon: Search,
    color: "#F59E0B",
    bgColor: "rgba(245, 158, 11, 0.15)",
    domain: "localhost:30008",
    category: "Platform",
    status: "live",
  },
  {
    id: "design",
    name: "DClaw Design",
    tagline: "AI-native design studio",
    description:
      "Generative design tool where prompts become editable vector designs. Create social media graphics, presentations, and brand assets with AI.",
    features: [
      "Prompt-to-canvas generation",
      "Smart brand-aligned variants",
      "SVG-based editable output",
      "React/Tailwind code export",
      "Conversational design editing",
    ],
    version: "0.1.0",
    icon: PenTool,
    color: "#EC4899",
    bgColor: "rgba(236, 72, 153, 0.15)",
    domain: "localhost:30013",
    category: "Design",
    status: "coming_soon",
  },
  {
    id: "video",
    name: "DClaw Video",
    tagline: "AI video director",
    description:
      "Script-to-video pipeline with local AI generation. Write a script, get storyboards, animated scenes, and auto-edited video with voiceover.",
    features: [
      "Script-to-scene breakdown",
      "Local FLUX + AnimateDiff generation",
      "Character consistency across scenes",
      "Auto voiceover with Kokoro TTS",
      "Template workflows (YouTube, Demo, Reel)",
    ],
    version: "0.1.0",
    icon: Video,
    color: "#EF4444",
    bgColor: "rgba(239, 68, 68, 0.15)",
    domain: "localhost:30014",
    category: "Media",
    status: "coming_soon",
  },
  {
    id: "research",
    name: "DClaw Research",
    tagline: "Deep research agent",
    description:
      "Local-first research agent that plans searches, builds knowledge graphs, and writes publication-ready reports with verifiable citations.",
    features: [
      "Editable research plans",
      "Interactive knowledge graph",
      "Local LLM synthesis",
      "Source verification & contradiction flags",
      "Academic / Business / Investment templates",
    ],
    version: "0.1.0",
    icon: Microscope,
    color: "#3B82F6",
    bgColor: "rgba(59, 130, 246, 0.15)",
    domain: "localhost:30015",
    category: "Research",
    status: "coming_soon",
  },
  {
    id: "legal",
    name: "DClaw Legal",
    tagline: "AI contract review & case law research",
    description:
      "Contract analysis, clause extraction, and case law research powered by local LLMs. Upload agreements, get risk scores, and find relevant precedents.",
    features: [
      "Contract risk scoring",
      "Clause extraction & comparison",
      "Case law semantic search",
      "Compliance checklist generation",
      "Redline suggestion engine",
    ],
    version: "0.1.0",
    icon: Scale,
    color: "#1E3A5F",
    bgColor: "rgba(30, 58, 95, 0.15)",
    domain: "localhost:3013",
    category: "Legal",
    status: "coming_soon",
  },
  {
    id: "finance",
    name: "DClaw Finance",
    tagline: "Financial modeling & risk analysis",
    description:
      "AI-powered financial modeling, forecasting, and risk analysis. Build scenarios, stress-test portfolios, and generate investment memos with local data privacy.",
    features: [
      "Financial forecast modeling",
      "Portfolio risk analysis",
      "Scenario planning & stress tests",
      "Investment memo generation",
      "Live market data integration",
    ],
    version: "0.1.0",
    icon: TrendingUp,
    color: "#059669",
    bgColor: "rgba(5, 150, 105, 0.15)",
    domain: "localhost:3014",
    category: "Finance",
    status: "coming_soon",
  },
  {
    id: "sales",
    name: "DClaw Sales",
    tagline: "CRM AI, email sequences & forecasting",
    description:
      "Intelligent sales automation that scores leads, writes email sequences, and forecasts pipeline revenue. Keeps your CRM data local and private.",
    features: [
      "AI lead scoring",
      "Automated email sequences",
      "Pipeline revenue forecasting",
      "CRM sync & enrichment",
      "Call transcript analysis",
    ],
    version: "0.1.0",
    icon: Target,
    color: "#D97706",
    bgColor: "rgba(217, 119, 6, 0.15)",
    domain: "localhost:3015",
    category: "Sales",
    status: "coming_soon",
  },
  {
    id: "support",
    name: "DClaw Support",
    tagline: "Ticket resolution & knowledge base AI",
    description:
      "AI-powered customer support that reads tickets, suggests resolutions, and searches your knowledge base. Local LLMs keep customer data private.",
    features: [
      "Auto ticket classification",
      "Knowledge base RAG search",
      "Suggested resolution drafts",
      "Sentiment analysis",
      "Escalation routing rules",
    ],
    version: "0.1.0",
    icon: Headphones,
    color: "#7C3AED",
    bgColor: "rgba(124, 58, 237, 0.15)",
    domain: "localhost:3016",
    category: "Support",
    status: "coming_soon",
  },
  {
    id: "hr",
    name: "DClaw HR",
    tagline: "Resume screening, interview prep & onboarding",
    description:
      "Intelligent HR assistant that screens resumes, generates interview questions, and builds onboarding plans. Reduces hiring bias with structured AI evaluation.",
    features: [
      "Resume parsing & scoring",
      "Structured interview questions",
      "Onboarding plan generation",
      "Policy Q&A chatbot",
      "Diversity analytics",
    ],
    version: "0.1.0",
    icon: Users,
    color: "#DB2777",
    bgColor: "rgba(219, 39, 119, 0.15)",
    domain: "localhost:3017",
    category: "HR",
    status: "coming_soon",
  },
  {
    id: "translate",
    name: "DClaw Translate",
    tagline: "Real-time translation & localization",
    description:
      "Local-first translation engine that preserves context, tone, and domain terminology. No cloud API required — runs entirely on your hardware.",
    features: [
      "Context-aware translation",
      "Domain glossary management",
      "Batch document translation",
      "Real-time speech translation",
      "Localization quality scoring",
    ],
    version: "0.1.0",
    icon: Languages,
    color: "#0891B2",
    bgColor: "rgba(8, 145, 178, 0.15)",
    domain: "localhost:3018",
    category: "Language",
    status: "coming_soon",
  },
  {
    id: "write",
    name: "DClaw Write",
    tagline: "Long-form writing, blogging & books",
    description:
      "AI writing assistant for blogs, books, emails, and social content. Maintains your voice, structures long-form narratives, and exports to any format.",
    features: [
      "Blog & book outliner",
      "Voice-matched rewriting",
      "Markdown & PDF export",
      "SEO-optimized drafting",
      "Citation & source management",
    ],
    version: "0.1.0",
    icon: FileText,
    color: "#4F46E5",
    bgColor: "rgba(79, 70, 229, 0.15)",
    domain: "localhost:3019",
    category: "Content",
    status: "coming_soon",
  },
  {
    id: "meet",
    name: "DClaw Meet",
    tagline: "Transcription, action items & summaries",
    description:
      "Meeting intelligence that transcribes audio, extracts action items, and builds searchable meeting memory. Runs locally for complete privacy.",
    features: [
      "Real-time transcription",
      "Auto action-item extraction",
      "Speaker identification",
      "Meeting search & Q&A",
      "Calendar integration",
    ],
    version: "0.1.0",
    icon: Mic,
    color: "#9333EA",
    bgColor: "rgba(147, 51, 234, 0.15)",
    domain: "localhost:3020",
    category: "Meetings",
    status: "coming_soon",
  },
  {
    id: "doc",
    name: "DClaw Doc",
    tagline: "Smart documents & collaborative editing",
    description:
      "AI-powered document editor with real-time collaboration, smart suggestions, and version control. Like Notion + Google Docs, but private and local.",
    features: [
      "Real-time collaborative editing",
      "AI suggestion sidebar",
      "Version history & diff",
      "Comment threads & mentions",
      "Export to PDF, Word, Markdown",
    ],
    version: "0.1.0",
    icon: FileEdit,
    color: "#2563EB",
    bgColor: "rgba(37, 99, 235, 0.15)",
    domain: "localhost:3021",
    category: "Documents",
    status: "coming_soon",
  },
  {
    id: "sheet",
    name: "DClaw Sheet",
    tagline: "AI-powered Excel alternative",
    description:
      "Spreadsheet intelligence that analyzes data, detects anomalies, and generates charts from natural language queries. Local-first with no data leaving your machine.",
    features: [
      "Natural language formulas",
      "Auto anomaly detection",
      "One-click chart generation",
      "CSV/Excel import & export",
      "Collaborative editing",
    ],
    version: "0.1.0",
    icon: Table2,
    color: "#16A34A",
    bgColor: "rgba(22, 163, 74, 0.15)",
    domain: "localhost:3022",
    category: "Spreadsheets",
    status: "coming_soon",
  },
  {
    id: "slide",
    name: "DClaw Slide",
    tagline: "AI-generated decks",
    description:
      "Presentation builder that turns outlines into polished slides. Auto-generates speaker notes, chooses layouts, and maintains brand consistency across every deck.",
    features: [
      "Outline-to-slide generation",
      "Auto speaker notes",
      "Brand template enforcement",
      "Export to PPT & PDF",
      "Presenter mode with timer",
    ],
    version: "0.1.0",
    icon: Presentation,
    color: "#EAB308",
    bgColor: "rgba(234, 179, 8, 0.15)",
    domain: "localhost:3023",
    category: "Presentations",
    status: "coming_soon",
  },
  {
    id: "email",
    name: "DClaw Email",
    tagline: "Smart inbox, auto-reply & scheduling",
    description:
      "AI email assistant that drafts replies, sorts priority mail, and schedules sends. Trained on your writing style and connected to your calendars.",
    features: [
      "Smart reply generation",
      "Priority inbox sorting",
      "Schedule send & reminders",
      "Tone matching your voice",
      "Unsubscribe automation",
    ],
    version: "0.1.0",
    icon: Mail,
    color: "#DC2626",
    bgColor: "rgba(220, 38, 38, 0.15)",
    domain: "localhost:3024",
    category: "Email",
    status: "coming_soon",
  },
  {
    id: "calendar",
    name: "DClaw Calendar",
    tagline: "AI scheduling & conflict resolution",
    description:
      "Intelligent calendar that finds optimal meeting times, resolves conflicts, and blocks focus time. Integrates with team schedules and respects time zones.",
    features: [
      "Optimal meeting finder",
      "Auto conflict resolution",
      "Focus time blocking",
      "Team availability sync",
      "Travel time estimation",
    ],
    version: "0.1.0",
    icon: CalendarDays,
    color: "#F97316",
    bgColor: "rgba(249, 115, 22, 0.15)",
    domain: "localhost:3025",
    category: "Scheduling",
    status: "coming_soon",
  },
  {
    id: "task",
    name: "DClaw Task",
    tagline: "Smart to-do & project management",
    description:
      "AI project manager that breaks down goals, estimates timelines, and surfaces blockers. Keeps teams aligned with automated standup summaries.",
    features: [
      "Goal breakdown & estimation",
      "Blocker detection",
      "Auto standup summaries",
      "Dependency mapping",
      "Sprint planning assistant",
    ],
    version: "0.1.0",
    icon: CheckSquare,
    color: "#84CC16",
    bgColor: "rgba(132, 204, 22, 0.15)",
    domain: "localhost:3026",
    category: "Productivity",
    status: "coming_soon",
  },
  {
    id: "wiki",
    name: "DClaw Wiki",
    tagline: "Internal Wikipedia with AI search",
    description:
      "Team knowledge base with semantic search, auto-generated summaries, and bidirectional linking. Turns scattered docs into a connected intelligence graph.",
    features: [
      "Semantic search",
      "Auto page summaries",
      "Bidirectional links",
      "Version history",
      "Access control & audit",
    ],
    version: "0.1.0",
    icon: BookOpen,
    color: "#06B6D4",
    bgColor: "rgba(6, 182, 212, 0.15)",
    domain: "localhost:3027",
    category: "Knowledge",
    status: "coming_soon",
  },
  {
    id: "data",
    name: "DClaw Data",
    tagline: "Natural language data analysis",
    description:
      "Analytics platform where you ask questions in plain English and get charts, insights, and predictions. Connects to databases, APIs, and flat files.",
    features: [
      "Natural language queries",
      "Auto chart generation",
      "Trend & outlier detection",
      "Database & API connectors",
      "Scheduled report generation",
    ],
    version: "0.1.0",
    icon: BarChart3,
    color: "#6366F1",
    bgColor: "rgba(99, 102, 241, 0.15)",
    domain: "localhost:3028",
    category: "Analytics",
    status: "coming_soon",
  },
  {
    id: "api",
    name: "DClaw API",
    tagline: "API design, testing & documentation",
    description:
      "Developer toolkit for designing, mocking, testing, and documenting APIs. Generates OpenAPI specs from code and keeps docs in sync automatically.",
    features: [
      "OpenAPI spec generation",
      "Auto mock server",
      "Contract testing",
      "Performance benchmarking",
      "Changelog automation",
    ],
    version: "0.1.0",
    icon: Globe,
    color: "#0D9488",
    bgColor: "rgba(13, 148, 136, 0.15)",
    domain: "localhost:3029",
    category: "Developer",
    status: "coming_soon",
  },
  {
    id: "test",
    name: "DClaw Test",
    tagline: "Automated testing & bug prediction",
    description:
      "QA intelligence that writes tests, predicts flaky failures, and prioritizes regression risk. Integrates with CI/CD to catch bugs before they ship.",
    features: [
      "Auto test generation",
      "Flaky test prediction",
      "Regression risk scoring",
      "CI/CD integration",
      "Visual diff testing",
    ],
    version: "0.1.0",
    icon: Bug,
    color: "#A855F7",
    bgColor: "rgba(168, 85, 247, 0.15)",
    domain: "localhost:3030",
    category: "QA",
    status: "coming_soon",
  },
  {
    id: "deploy",
    name: "DClaw Deploy",
    tagline: "CI/CD pipeline builder",
    description: "CI/CD pipeline builder powered by local AI.",
    features: [
      "Pipeline generation from repo URL",
      "Multi-stage build configs",
      "Auto rollback on failure",
      "Environment promotion rules",
      "GitOps integration",
    ],
    version: "0.1.0",
    icon: Rocket,
    color: "#0EA5E9",
    bgColor: "rgba(14, 165, 233, 0.15)",
    domain: "localhost:3031",
    category: "DevOps",
    status: "coming_soon",
  },
  {
    id: "monitor",
    name: "DClaw Monitor",
    tagline: "AI-powered alerting & root cause",
    description: "AI-powered alerting & root cause powered by local AI.",
    features: [
      "Real-time health checks",
      "Anomaly detection",
      "Latency & error tracking",
      "Auto root cause analysis",
      "PagerDuty/Slack alerts",
    ],
    version: "0.1.0",
    icon: Activity,
    color: "#6366F1",
    bgColor: "rgba(99, 102, 241, 0.15)",
    domain: "localhost:3032",
    category: "Observability",
    status: "coming_soon",
  },
  {
    id: "secure",
    name: "DClaw Secure",
    tagline: "Threat detection & vulnerability scanning",
    description: "Threat detection & vulnerability scanning powered by local AI.",
    features: [
      "Web/API/container scanning",
      "Risk scoring",
      "CVE database lookup",
      "Remediation suggestions",
      "Compliance mapping",
    ],
    version: "0.1.0",
    icon: Shield,
    color: "#EF4444",
    bgColor: "rgba(239, 68, 68, 0.15)",
    domain: "localhost:3033",
    category: "Security",
    status: "coming_soon",
  },
  {
    id: "backup",
    name: "DClaw Backup",
    tagline: "Intelligent backup & recovery",
    description: "Intelligent backup & recovery powered by local AI.",
    features: [
      "Automated backup scheduling",
      "Compression & deduplication",
      "Point-in-time recovery",
      "Cross-region replication",
      "Restore testing",
    ],
    version: "0.1.0",
    icon: Database,
    color: "#84CC16",
    bgColor: "rgba(132, 204, 22, 0.15)",
    domain: "localhost:3034",
    category: "Infrastructure",
    status: "coming_soon",
  },
  {
    id: "migrate",
    name: "DClaw Migrate",
    tagline: "Cloud migration assistant",
    description: "Cloud migration assistant powered by local AI.",
    features: [
      "Migration complexity scoring",
      "Downtime estimation",
      "Risk assessment",
      "Cost forecasting",
      "Rollback planning",
    ],
    version: "0.1.0",
    icon: ArrowRightLeft,
    color: "#F59E0B",
    bgColor: "rgba(245, 158, 11, 0.15)",
    domain: "localhost:3035",
    category: "Infrastructure",
    status: "coming_soon",
  },
  {
    id: "cost",
    name: "DClaw Cost",
    tagline: "Cloud cost optimization",
    description: "Cloud cost optimization powered by local AI.",
    features: [
      "Multi-cloud spend tracking",
      "Savings recommendations",
      "Anomaly detection",
      "Reserved instance planning",
      "Budget alerts",
    ],
    version: "0.1.0",
    icon: DollarSign,
    color: "#10B981",
    bgColor: "rgba(16, 185, 129, 0.15)",
    domain: "localhost:3036",
    category: "FinOps",
    status: "coming_soon",
  },
  {
    id: "carbon",
    name: "DClaw Carbon",
    tagline: "Carbon footprint tracking",
    description: "Carbon footprint tracking powered by local AI.",
    features: [
      "Scope 1/2/3 breakdown",
      "Reduction target setting",
      "Supplier emissions",
      "Offset tracking",
      "ESG reporting",
    ],
    version: "0.1.0",
    icon: Leaf,
    color: "#22C55E",
    bgColor: "rgba(34, 197, 94, 0.15)",
    domain: "localhost:3037",
    category: "Sustainability",
    status: "coming_soon",
  },
  {
    id: "compliance",
    name: "DClaw Compliance",
    tagline: "GDPR, SOC2, HIPAA automation",
    description: "GDPR, SOC2, HIPAA automation powered by local AI.",
    features: [
      "Framework assessments",
      "Control mapping",
      "Gap analysis",
      "Evidence collection",
      "Audit readiness",
    ],
    version: "0.1.0",
    icon: FileCheck,
    color: "#7C3AED",
    bgColor: "rgba(124, 58, 237, 0.15)",
    domain: "localhost:3038",
    category: "Governance",
    status: "coming_soon",
  },
  {
    id: "audit",
    name: "DClaw Audit",
    tagline: "Automated audit trails",
    description: "Automated audit trails powered by local AI.",
    features: [
      "Event capture & storage",
      "Anomaly flagging",
      "Compliance dashboards",
      "Immutable logs",
      "Export & reporting",
    ],
    version: "0.1.0",
    icon: ScanLine,
    color: "#EC4899",
    bgColor: "rgba(236, 72, 153, 0.15)",
    domain: "localhost:3039",
    category: "Governance",
    status: "coming_soon",
  },
  {
    id: "policy",
    name: "DClaw Policy",
    tagline: "Policy management & enforcement",
    description: "Policy management & enforcement powered by local AI.",
    features: [
      "Policy authoring & versioning",
      "Coverage gap detection",
      "Conflict analysis",
      "Approval workflows",
      "Employee attestation",
    ],
    version: "0.1.0",
    icon: ScrollText,
    color: "#3B82F6",
    bgColor: "rgba(59, 130, 246, 0.15)",
    domain: "localhost:3040",
    category: "Governance",
    status: "coming_soon",
  },
  {
    id: "train",
    name: "DClaw Train",
    tagline: "Employee training & certification tracking",
    description: "Employee training & certification tracking powered by local AI.",
    features: [
      "Course authoring",
      "Progress tracking",
      "Certification expiry alerts",
      "Competency mapping",
      "Skills gap analysis",
    ],
    version: "0.1.0",
    icon: GraduationCap,
    color: "#F97316",
    bgColor: "rgba(249, 115, 22, 0.15)",
    domain: "localhost:3041",
    category: "L&D",
    status: "coming_soon",
  },
  {
    id: "recruit",
    name: "DClaw Recruit",
    tagline: "Job posting, candidate ranking",
    description: "Job posting, candidate ranking powered by local AI.",
    features: [
      "Job description optimization",
      "Resume parsing & scoring",
      "Interview scheduling",
      "Collaborative hiring",
      "Time-to-fill analytics",
    ],
    version: "0.1.0",
    icon: UserPlus,
    color: "#14B8A6",
    bgColor: "rgba(20, 184, 166, 0.15)",
    domain: "localhost:3042",
    category: "Talent",
    status: "coming_soon",
  },
  {
    id: "onboard",
    name: "DClaw Onboard",
    tagline: "Automated employee onboarding",
    description: "Automated employee onboarding powered by local AI.",
    features: [
      "Checklist automation",
      "Document collection",
      "Buddy assignment",
      "Day-1 scheduling",
      "Progress tracking",
    ],
    version: "0.1.0",
    icon: UserCheck,
    color: "#8B5CF6",
    bgColor: "rgba(139, 92, 246, 0.15)",
    domain: "localhost:3043",
    category: "HR",
    status: "coming_soon",
  },
  {
    id: "offboard",
    name: "DClaw Offboard",
    tagline: "Secure offboarding automation",
    description: "Secure offboarding automation powered by local AI.",
    features: [
      "Access revocation",
      "Asset return tracking",
      "Knowledge transfer",
      "Exit interviews",
      "Compliance verification",
    ],
    version: "0.1.0",
    icon: UserX,
    color: "#64748B",
    bgColor: "rgba(100, 116, 139, 0.15)",
    domain: "localhost:3044",
    category: "HR",
    status: "coming_soon",
  },
  {
    id: "assets",
    name: "DClaw Assets",
    tagline: "Hardware and software asset management",
    description: "Hardware and software asset management powered by local AI.",
    features: [
      "Asset discovery & tracking",
      "Warranty management",
      "Deprecation alerts",
      "Assignment history",
      "Audit reports",
    ],
    version: "0.1.0",
    icon: Package,
    color: "#EAB308",
    bgColor: "rgba(234, 179, 8, 0.15)",
    domain: "localhost:3045",
    category: "IT",
    status: "coming_soon",
  },
  {
    id: "network",
    name: "DClaw Network",
    tagline: "Network monitoring and optimization",
    description: "Network monitoring and optimization powered by local AI.",
    features: [
      "Topology mapping",
      "Latency monitoring",
      "Bandwidth analysis",
      "Anomaly detection",
      "Optimization suggestions",
    ],
    version: "0.1.0",
    icon: Network,
    color: "#0891B2",
    bgColor: "rgba(8, 145, 178, 0.15)",
    domain: "localhost:3046",
    category: "IT",
    status: "coming_soon",
  },
  {
    id: "inventory",
    name: "DClaw Inventory",
    tagline: "Supply chain intelligence",
    description: "Supply chain intelligence powered by local AI.",
    features: [
      "Stock level tracking",
      "Reorder automation",
      "Demand forecasting",
      "Lead time analysis",
      "Warehouse optimization",
    ],
    version: "0.1.0",
    icon: Boxes,
    color: "#A855F7",
    bgColor: "rgba(168, 85, 247, 0.15)",
    domain: "localhost:3047",
    category: "Operations",
    status: "coming_soon",
  },
  {
    id: "forecast",
    name: "DClaw Forecast",
    tagline: "Demand forecasting",
    description: "Demand forecasting powered by local AI.",
    features: [
      "Statistical forecasting",
      "Seasonality detection",
      "Confidence intervals",
      "Risk adjustments",
      "What-if scenarios",
    ],
    version: "0.1.0",
    icon: TrendingUp,
    color: "#0D9488",
    bgColor: "rgba(13, 148, 136, 0.15)",
    domain: "localhost:3048",
    category: "Operations",
    status: "coming_soon",
  },
  {
    id: "quality",
    name: "DClaw Quality",
    tagline: "Quality control AI",
    description: "Quality control AI powered by local AI.",
    features: [
      "Batch inspection",
      "Defect classification",
      "Pass rate tracking",
      "Trend analysis",
      "Corrective actions",
    ],
    version: "0.1.0",
    icon: Award,
    color: "#DC2626",
    bgColor: "rgba(220, 38, 38, 0.15)",
    domain: "localhost:3049",
    category: "Manufacturing",
    status: "coming_soon",
  },
  {
    id: "maintenance",
    name: "DClaw Maintenance",
    tagline: "Predictive maintenance",
    description: "Predictive maintenance powered by local AI.",
    features: [
      "Asset health scoring",
      "Failure prediction",
      "Maintenance scheduling",
      "Spare parts planning",
      "Downtime reduction",
    ],
    version: "0.1.0",
    icon: Wrench,
    color: "#4B5563",
    bgColor: "rgba(75, 85, 99, 0.15)",
    domain: "localhost:3050",
    category: "Operations",
    status: "coming_soon",
  },
  {
    id: "route",
    name: "DClaw Route",
    tagline: "Route optimization",
    description: "Route optimization powered by local AI.",
    features: [
      "Multi-stop optimization",
      "Real-time traffic",
      "Fuel cost estimation",
      "Delivery time prediction",
      "Driver assignment",
    ],
    version: "0.1.0",
    icon: Map,
    color: "#2563EB",
    bgColor: "rgba(37, 99, 235, 0.15)",
    domain: "localhost:3051",
    category: "Logistics",
    status: "coming_soon",
  },
  {
    id: "warehouse",
    name: "DClaw Warehouse",
    tagline: "Warehouse automation",
    description: "Warehouse automation powered by local AI.",
    features: [
      "Layout optimization",
      "Picking efficiency",
      "Space utilization",
      "Bottleneck detection",
      "Automation ROI",
    ],
    version: "0.1.0",
    icon: Building2,
    color: "#D97706",
    bgColor: "rgba(217, 119, 6, 0.15)",
    domain: "localhost:3052",
    category: "Logistics",
    status: "coming_soon",
  },
  {
    id: "fleet",
    name: "DClaw Fleet",
    tagline: "Fleet management",
    description: "Fleet management powered by local AI.",
    features: [
      "Vehicle tracking",
      "Fuel efficiency",
      "Maintenance alerts",
      "Route compliance",
      "Driver safety",
    ],
    version: "0.1.0",
    icon: Truck,
    color: "#7C3AED",
    bgColor: "rgba(124, 58, 237, 0.15)",
    domain: "localhost:3053",
    category: "Logistics",
    status: "coming_soon",
  },
  {
    id: "energy",
    name: "DClaw Energy",
    tagline: "Energy consumption optimization",
    description: "Energy consumption optimization powered by local AI.",
    features: [
      "Usage monitoring",
      "Peak hour analysis",
      "Wastage detection",
      "Savings opportunities",
      "Renewable integration",
    ],
    version: "0.1.0",
    icon: Zap,
    color: "#FACC15",
    bgColor: "rgba(250, 204, 21, 0.15)",
    domain: "localhost:3054",
    category: "Utilities",
    status: "coming_soon",
  },
  {
    id: "water",
    name: "DClaw Water",
    tagline: "Water management",
    description: "Water management powered by local AI.",
    features: [
      "Consumption tracking",
      "Leak detection",
      "Irrigation efficiency",
      "Recycling potential",
      "Zone analysis",
    ],
    version: "0.1.0",
    icon: Droplets,
    color: "#3B82F6",
    bgColor: "rgba(59, 130, 246, 0.15)",
    domain: "localhost:3055",
    category: "Utilities",
    status: "coming_soon",
  },
  {
    id: "waste",
    name: "DClaw Waste",
    tagline: "Waste reduction AI",
    description: "Waste reduction AI powered by local AI.",
    features: [
      "Waste stream audit",
      "Recycling rate tracking",
      "Compostable analysis",
      "Reduction recommendations",
      "Circular economy metrics",
    ],
    version: "0.1.0",
    icon: Recycle,
    color: "#65A30D",
    bgColor: "rgba(101, 163, 13, 0.15)",
    domain: "localhost:3056",
    category: "Sustainability",
    status: "coming_soon",
  },
  {
    id: "building",
    name: "DClaw Building",
    tagline: "Smart building management",
    description: "Smart building management powered by local AI.",
    features: [
      "Occupancy optimization",
      "HVAC efficiency",
      "Maintenance backlog",
      "Tenant satisfaction",
      "Energy benchmarking",
    ],
    version: "0.1.0",
    icon: Building,
    color: "#475569",
    bgColor: "rgba(71, 85, 105, 0.15)",
    domain: "localhost:3057",
    category: "Real Estate",
    status: "coming_soon",
  },
  {
    id: "space",
    name: "DClaw Space",
    tagline: "Office space optimization",
    description: "Office space optimization powered by local AI.",
    features: [
      "Floor plan analysis",
      "Seating efficiency",
      "Collaboration scoring",
      "Quiet zone planning",
      "Redesign suggestions",
    ],
    version: "0.1.0",
    icon: LayoutGrid,
    color: "#9333EA",
    bgColor: "rgba(147, 51, 234, 0.15)",
    domain: "localhost:3058",
    category: "Real Estate",
    status: "coming_soon",
  },
  {
    id: "lease",
    name: "DClaw Lease",
    tagline: "Lease management",
    description: "Lease management powered by local AI.",
    features: [
      "Terms extraction",
      "Rent escalation tracking",
      "Renewal risk scoring",
      "Market comparison",
      "Clause analysis",
    ],
    version: "0.1.0",
    icon: FileSignature,
    color: "#DB2777",
    bgColor: "rgba(219, 39, 119, 0.15)",
    domain: "localhost:3059",
    category: "Real Estate",
    status: "coming_soon",
  },
  {
    id: "vendor",
    name: "DClaw Vendor",
    tagline: "Vendor evaluation and management",
    description: "Vendor evaluation and management powered by local AI.",
    features: [
      "Performance scoring",
      "Risk assessment",
      "Contract tracking",
      "Alternative sourcing",
      "Renewal negotiation",
    ],
    version: "0.1.0",
    icon: Handshake,
    color: "#059669",
    bgColor: "rgba(5, 150, 105, 0.15)",
    domain: "localhost:3060",
    category: "Procurement",
    status: "coming_soon",
  },
];
